// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoyaznsjctkdkbyksfle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFveWF6bnNqY3RrZGtieWtzZmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDYyNzAsImV4cCI6MjA3NDEyMjI3MH0.OJMilt-jjku2vfIL4XM_qWIp5Ksnnp6REGb4wrI0flE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});